services:
  postgres:
    image: postgres:latest
    container_name: postgres_netspider
    restart: unless-stopped
    environment:
      POSTGRES_DB: netspider
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
