services:
  postgres:
    container_name: netspider_postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: netspider
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./v00.sql:/docker-entrypoint-initdb.d/v00.sql
      - ./import_csv.sh:/docker-entrypoint-initdb.d/import_csv.sh
      - ./data:/data
    entrypoint: ["/bin/bash", "-c", "chmod +x /docker-entrypoint-initdb.d/import_csv.sh && exec docker-entrypoint.sh postgres"]

volumes:
  pgdata:
